version: '3'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/core
    ports:
      - 8000:8000
    image: app:django
    depends_on:
      - db
    container_name: django_container
  db:
    image: mysql:5.7
    ports:
      - 3366:3306
    environment:
      MYSQL_DATABASE: 'db_django'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
    restart: always
    volumes:
      - ./db_django:/var/lib/mysql