# Generated by Django 4.1 on 2022-08-07 06:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app_notice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='crated_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='crated at'),
            preserve_default=False,
        ),
    ]
