# Generated by Django 4.1 on 2022-08-07 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_notice', '0002_notice_crated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Title:'),
        ),
    ]
