# Generated by Django 4.1 on 2022-08-11 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_notice', '0003_alter_notice_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='is_public',
            field=models.BooleanField(default=False, verbose_name='Public'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='crated_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Crated at'),
        ),
    ]
